# Generated by Django 3.0.3 on 2020-06-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_one_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
