# Generated by Django 3.0.3 on 2020-06-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200625_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_third_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_two_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
